version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: lern/lern-web:local
        stdin_open: true
        volumes:
            - node_modules:/app/node_modules
            - ./:/app
        ports:
            - 80:80
        environment:
            - PORT=80
            - NODE_ENV=${NODE_ENV}

volumes:
    node_modules:
