name: Tests

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version  }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
    - name: build app
      run: npm run build --if-present
    - name: run test
      run: npm test